### ISSUE TITLE
Workflow example to track mail clicks ?

### ISSUE THREAD

**Issue by giannik** [lampersky/OrchardCoreWorkflowsExamples#1]
Firstly, your examples and very informative in learning workflows for orchard core.
Thanks.
I wish to build the following workflow : 
A workflow that sends emails to a list of recipients .
The email has 2 links to accept or reject an offer.

When User clicks on either accept or reject link on the email it will trigger another workflow (I think the incoming request event is appropriate here) that will log the recipients reponse in a custom table in orchard that will hold the recipients email and response (yes /no) to gather some statistics later on.

Is a workflow like this possible ?
Thanks @lampersky

**Comment by lampersky** [comment]
Hi @giannik at first glance it sounds doable.

I'm thinking about sth like this:

**First workflow** which receives a list of emails through post request and starts sub workflows:
![image](https://user-images.githubusercontent.com/6403130/172844377-c6b2cb77-e405-415b-b775-28a7eadb1b58.png)

**Second workflow** which performs email send and clicks handling:
![image](https://user-images.githubusercontent.com/6403130/172844485-865f4319-3473-4588-8faf-0db6c9f393f4.png)
